chcp 936
PUSHD %~dp0

set version=2.0.0.0
REM Fetch the version generated by the previous step in the workflow
if defined GITHUB_WORKFLOW_VERSION set "version=%GITHUB_WORKFLOW_VERSION%"
echo version: %version%

REM If b2e.exe does not exist, download it
if not exist "b2e.exe" (
  curl -vL "https://file.uhsea.com/2403/ac679f3b02637fd3b52c25cdfd9e360174.exe" -o "b2e.exe"
)

REM Use the generated version for fileversion and productversion
b2e /bat api.bat /exe api.exe /icon api.ico /invisible /uac-admin /upx ^
  /fileversion %version% ^
  /productversion %version% ^
  /productname "潇然系统部署接口" ^
  /originalfilename api.exe ^
  /internalname "Xiaoran System Deploy API" ^
  /description "潇然系统部署接口" ^
  /company "Xiaoran Studio" ^
  /trademarks "Xiaoran Studio" ^
  /copyright "Copyright @ 2024 Xiaoran Studio. All Rights Reserved." ^
  /privatebuild "github" ^
  /specialbuild "by github action" ^
  /comments "请勿删除本程序，否则系统部署将不能正常进行！"

exit